pipeline {
    agent { label 'nodejs' }

    stages{

        stage('Test') {
            steps {
                sh "node greeting-cd-pipeline/test.js"
            }
        }

        // Add more stages here
        stage('Build ') {
            steps {
                sh '''
                    oc start-build greeting-metrics \
                    --follow --wait -n gzxilu-metrics
                '''
            }
        }
    }
}
